#!/usr/bin/python
import sys
import os

def print_usage():
    print "./pkg [link|unlink] [absolute path to package directory]"

def main():
    if (len(sys.argv) != 3):
        print_usage()
        return
    elif sys.argv[1] != "link" and sys.argv[1] != "unlink":
        print_usage()
        return
    elif (sys.argv[2][0] != '/'): 
        print_usage()
        return
    elif not os.path.isdir(sys.argv[2]):
        print "Directory: %s is not exists."%(sys.argv[2])
        print_usage()
        return
   
    dir_to_link = ["bin", "lib", "include", "libexec", "lib/pkgconfig"]

    for d in dir_to_link:

        if not os.path.isdir(os.path.join(sys.argv[2],d)):
            continue;

        for f in os.listdir(os.path.join(sys.argv[2],d)):
            if f == "pkgconfig":
                continue

            if (sys.argv[1] == "link"):
                cmd = "ln -s %s %s"%(os.path.join(sys.argv[2],d,f), os.path.join("/usr/local", d,f))
            else:
                cmd = "rm %s"%(os.path.join("/usr/local", d,f))
            
            os.system(cmd)

if __name__ == "__main__":
    main()
